version: "3.2"
services:
  postgres:
    container_name: asyauqi_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: asyauqi_test
      POSTGRES_DB: asyauqi_test
      POSTGRES_PASSWORD: asyauqi_test
    ports:
      - 5432:5432
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: asyauqi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy