// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/employees/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get all employee data",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Success"
                                },
                                "data": {
                                    "type": "array",
                                    "description": "employees data",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "integer",
                                                "description": "Employee ID"
                                            },
                                            "first_name": {
                                                "type": "string",
                                                "description": "Employee's first name"
                                            },
                                            "last_name": {
                                                "type": "string",
                                                "description": "Employee's last name"
                                            },
                                            "email": {
                                                "type": "string",
                                                "description": "Employee's email"
                                            },
                                            "hire_date": {
                                                "type": "string",
                                                "description": "Employee's hire date (YYYY-MM-DD)"
                                            }
                                        }
                                    },
                                    "example": [
                                        {
                                            "id": "1",
                                            "first_name": "John",
                                            "last_name": "Bob",
                                            "email": "john@example.com",
                                            "hire_date": "2022-12-31"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "timeout when retrieving data to database"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Insert new employee data",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "description": "New employee data",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "first_name": {
                                    "type": "string",
                                    "description": "First name",
                                    "example": "John",
                                    "required": true
                                },
                                "last_name": {
                                    "type": "string",
                                    "description": "Last name",
                                    "example": "Bob",
                                    "required": true
                                },
                                "email": {
                                    "type": "e",
                                    "description": "Email address",
                                    "example": "john@example.com",
                                    "required": true
                                },
                                "hire_date": {
                                    "type": "string",
                                    "description": "Hire date (YYYY-MM-DD)",
                                    "example": "2022-12-31",
                                    "required": true
                                }
                            },
                            "required": [
                                "first_name",
                                "last_name",
                                "email",
                                "hire_date"
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Success"
                                },
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "description": "Employee ID"
                                        },
                                        "first_name": {
                                            "type": "string",
                                            "description": "Employee's first name"
                                        },
                                        "last_name": {
                                            "type": "string",
                                            "description": "Employee's last name"
                                        },
                                        "email": {
                                            "type": "string",
                                            "description": "Employee's email"
                                        },
                                        "hire_date": {
                                            "type": "string",
                                            "description": "Employee's hire date (YYYY-MM-DD)"
                                        }
                                    },
                                    "example": {
                                        "id": "1",
                                        "first_name": "John",
                                        "last_name": "Bob",
                                        "email": "john@example.com",
                                        "hire_date": "2022-12-31"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "invalid hire_date format"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "timeout when retrieving data to database"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get all employee data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Success"
                                },
                                "data": {
                                    "type": "object",
                                    "description": "employees data",
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "description": "Employee ID"
                                        },
                                        "first_name": {
                                            "type": "string",
                                            "description": "Employee's first name"
                                        },
                                        "last_name": {
                                            "type": "string",
                                            "description": "Employee's last name"
                                        },
                                        "email": {
                                            "type": "string",
                                            "description": "Employee's email"
                                        },
                                        "hire_date": {
                                            "type": "string",
                                            "description": "Employee's hire date (YYYY-MM-DD)"
                                        }
                                    },
                                    "example": [
                                        {
                                            "id": "1",
                                            "first_name": "John",
                                            "last_name": "Bob",
                                            "email": "john@example.com",
                                            "hire_date": "2022-12-31"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "id not valid"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "timeout when retrieving data to database"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get all employee data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "in": "body",
                        "description": "Update employee data",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "first_name": {
                                    "type": "string",
                                    "description": "First name",
                                    "example": "John",
                                    "required": true
                                },
                                "last_name": {
                                    "type": "string",
                                    "description": "Last name",
                                    "example": "Bob",
                                    "required": true
                                },
                                "email": {
                                    "type": "e",
                                    "description": "Email address",
                                    "example": "john@example.com",
                                    "required": true
                                },
                                "hire_date": {
                                    "type": "string",
                                    "description": "Hire date (YYYY-MM-DD)",
                                    "example": "2022-12-31",
                                    "required": true
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Success"
                                },
                                "data": {
                                    "type": "object",
                                    "description": "Updated employee data",
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "description": "Employee ID"
                                        },
                                        "first_name": {
                                            "type": "string",
                                            "description": "Employee's first name"
                                        },
                                        "last_name": {
                                            "type": "string",
                                            "description": "Employee's last name"
                                        },
                                        "email": {
                                            "type": "string",
                                            "description": "Employee's email"
                                        },
                                        "hire_date": {
                                            "type": "string",
                                            "description": "Employee's hire date (YYYY-MM-DD)"
                                        }
                                    },
                                    "example": [
                                        {
                                            "id": "1",
                                            "first_name": "John",
                                            "last_name": "Bob",
                                            "email": "john@example.com",
                                            "hire_date": "2022-12-31"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "id not valid"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "timeout when retrieving data to database"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Delete employee data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Success"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "id not valid"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "description": "status success or failure",
                                    "example": "Failed"
                                },
                                "message": {
                                    "type": "string",
                                    "description": "error description",
                                    "example": "timeout when retrieving data to database"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Employee Management.",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
